services:
  # Home Assistant
  homeassistant:    
    container_name: home-assistant
    build: .
    environment:
      - TZ=Europe/Berlin
      - DISABLE_JEMALLOC=true
      - MPLCONFIGDIR=/mplconfig
    volumes:
      # Local path where your home assistant config will be stored
      - ./homeassistant/.storage:/config/.storage
      # Local path where your sqlite db file will be stored
      - ./homeassistant/db:/config/db
      # use host timezone setting
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123

  # EVCC
  evcc:
    command:
      - evcc
    container_name: evcc
    image: evcc/evcc:latest
    ports:
      - 7070:7070/tcp
      - 8887:8887/tcp
      - 7090:7090/udp
      - 9522:9522/udp
    volumes:
      - ./evcc/evcc.yaml:/etc/evcc.yaml
      - ./evcc:/root/.evcc
    restart: unless-stopped
    depends_on:
      homeassistant:
        condition: service_started
