services:
  # HomeAssistant
  homeassistant:    
#    container_name: home-assistant
#    image: "ghcr.io/home-assistant/home-assistant:stable"
    build: .
    environment:
      - TZ=Europe/Berlin
      - DISABLE_JEMALLOC=true
      - MPLCONFIGDIR=/mplconfig
    volumes:
      # Local path where your home assistant config will be stored
      - ./homeassistant/.storage:/config/.storage
      # Local path where your sqlite db file will be stored
      - ./homeassistant/db:/config/db
      # use host timezone setting
      - /etc/localtime:/etc/localtime:ro
      # add kia_uvo custom component
#      - ./kia_uvo/custom_components/:/config/custom_components
      # add hyundai_kia_connect_api package directly to kia_uvo custom component (use Kia-EU-login-fix branch)
#      - ./hyundai_kia_connect_api/hyundai_kia_connect_api/:/config/custom_components/kia_uvo/hyundai_kia_connect_api
      # override kia_uvo manifest.json to avoit pip package installing for hyundai_kia_connect_api package
#      - ./kia_uvo_manifest.json:/config/custom_components/kia_uvo/manifest.json
#      - type: bind
#        source: ./kia_uvo_manifest.json
#        target: /config/custom_components/kia_uvo/mainifest.json
    restart: unless-stopped
#    command: cat cat
    ports:
      - 8123:8123
    # network_mode: host

  evcc:
    command:
      - evcc
    container_name: evcc
    image: evcc/evcc:latest
    ports:
      - 7070:7070/tcp
      - 8887:8887/tcp
      - 7090:7090/udp
      - 9522:9522/udp
    volumes:
      - ./evcc/evcc.yaml:/etc/evcc.yaml
      - ./evcc:/root/.evcc
    restart: unless-stopped
